#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#undef TAPPING_TERM
#define TAPPING_TERM 200

//#define TAPPING_TERM_PER_KEY

#define QUICK_TAP_TERM 100

//#undef BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#undef DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
//#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#endif
